# Environment including Python, pip, numpy, tqdm, pygame, pandas
name: EVOMAN
channels:
  - defaults
dependencies:
  - python=3.11.5
  - pip=21.2.4
  - numpy
  - pip:
    - pygame==2.0.2
    - pandas==1.3.3
    - tqdm==4.62.3
