# Environment including Python, pip, numpy, tqdm, pygame, pandas, and scipy
name: EVOMAN
channels:
  - defaults
dependencies:
  - python=3.11.5
  - pip=23.2.1
  - numpy
  - pip:
    - tqdm
    - pygame
    - pandas
    - scipy
